version: "3.9"

# GPU override for Ollama - use with: docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up

services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all

  ollama-init:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - NVIDIA_VISIBLE_DEVICES=all